### PR TITLE
Login/Signin Feedback To Wrong Input/ Modal View for Home Page / Feed…

### PR DESCRIPTION
**Pull request by beaverseven**
Live feedback is given to both Login and Signup forms when incorrect input is typed in utilizing a new package called Formik. The user can now click on the swipeable card for the modal view of the details. The card also gives live feedback with the new swiping style. 

-Changes to Login/Sign-in where the forms give live feedback to when the user types in an invalid form input.
-Changes to Signup.js where the user was able to insepct element and remove the key from the console and be able to sign up without typing a user name using Formik package. Now there is more security on the signup process. 
-Changes to Login.js where feedback is given if the wrong username/password is typed in. Before this was not implemented. -Changes to SwipeableCard.js where the live feeedback is given on a swipe, and when the user clicks the bottom of the card, the modal view of the place pops up/ 
-Changes to corresponding CSS files for styling purposes, such as in Login.module.css where the input for the password does not overlap the reveal icon on the password form. 
-Changes to CardDeck.js, Card.js to incorporate the modal view. 
-Added Text.js for favorite details because instead of using the code in favorite details I just put it in a separate file for clarity purposes.

Apologies for the big update, should have been separated into separate PULL REQUESTS.

### CODE REVIEW

**Review by Kirazuto7 — CHANGES_REQUESTED** [review]
Resolve the merge conflicts first

**Review by JChen0915 — CHANGES_REQUESTED** [review]
Resolve the merge conflicts

**Review by Kirazuto7 — APPROVED** [review]
Was a long journey to rebase, but the light is finally here. Next time separate your implementations into different branches

**Review by JChen0915 — APPROVED** [review]
He is finally free. A lot of this should have been split up still

**Review by JChen0915 — APPROVED** [review]
He is finally free. A lot of this should have been split up still

**Review by chizy7 — APPROVED** [review]
Merging this but I recommend separating changes in several prs to avoid large pr committing previous commits. I will test after merging and if something is broken, I will revert.

**Pull request merged**
