### PR TITLE
revamped preferences and made style changes

### PR DESCRIPTION
**Pull request by Kirazuto7**
Changes:

Index.js: Added louis-george-cafe font

AppNavbar.js:  Updated the styling for the navbar according to David's design. Added gradient background and moved the links to the right for when the user is logged in. Changed the app icon. Also loads the user's profile picture to the navbar profile picture.

HomepageWithCards.js: Updated styling and removed info button

Preferences.js: Updated styling for preferences page. Removed the bootstrap button group and replaced it with my own custom made button groups for setting categories. The Bootstrap button group was difficult to apply custom styling towards especially for the active state since the active state was tied towards the ButtonGroup component rather than the individual Button itself. The new custom button group utilizes a "map-like" object for efficient toggling and converts the data to an array on save changes for only the buttons that are turned on.

### CODE REVIEW

**Review by beaverseven — APPROVED** [review]
Really nice update, really like how everything is more clean now.

**Review by JChen0915 — APPROVED** [review]
Looks good, but is the font's png file necessary?

**Comment by Kirazuto7** [comment]
It just came with the download. It's not necessary

**Comment by Kirazuto7** [comment]
> Looks good, but is the font's png file necessary? 

It just came with the download. It's not necessary

**Pull request merged**
