### PR TITLE
Js profile

### PR DESCRIPTION
**Pull request by Kirazuto7**
Changes:

App.js: Pass the location state to Profile

Avatar_Upload.jsx: Fixed the image upload to firebase storage and setting the image to the profile image tag

UserInfo.jsx: Fixed the parsing for the user location using the google maps api and passed location props. Separated the latitude and longitude values from the props value. Also sets the image for the user profile from firebase storage if it exists. 

UpdatePassword.jsx: Changed the confirm password field to confirm the new password instead of current

### CODE REVIEW

**Review by caid4134 — APPROVED** [review]
Changes look good, nice job on this.

**Review by chizy7 — APPROVED** [review]
Everything looks good and well implemented. Great job!

**Review by JChen0915 — APPROVED** [review]
Looks good, change to more natural usage of password confirmation is nice.

**Review by beaverseven — APPROVED** [review]
Good work! I like how you utilized Routing as well as uploading the profile picture with feedback messages,

**Pull request merged**
